### PR TITLE
Add Fig as an installation method to the README

### PR DESCRIPTION
**Pull request by ibayramli2001**
- [ ] This compdef is not already available in zsh.
- [ ] This compdef is not already available in their original project.
- [ ] I am the original author, or I have authorization to submit this work.
- [ ] This is a finished work.
- [ ] It has a header containing authors, status and origin of the script.
- [ ] It has a license header or I accept that it will be licensed under the terms of the Zsh license.

## PR Description

The [Fig Plugin Store](https://fig.io/plugins) supports 1-click install for 400+ shell plugins. We have over 100k users, thousands of whom manage their shell configuration with Fig.

Zsh completions is one of the most popular plugins on our store (it's on our front page!), so we'd really love to have Fig listed as a download method on your readme.

Thanks so much and please let me know if you have any questions!

### CODE REVIEW

**Comment by syohex** [comment]
Thanks

**Comment by z0rc** [comment]
Can this be reverted please? This text is pure advertisement with zero value. There a no 

>over 100k users, thousands of whom manage their shell configuration with Fig

Link is just landing page and external image can be used for tracking.

**Comment by syohex** [comment]
@z0rc I see. I reverted it at https://github.com/zsh-users/zsh-completions/commit/45cb3becd8ca388505910a6cc6917c07b3aee4a9.

I'll check other PR comments and their opinions.

- https://github.com/zsh-users/zsh-syntax-highlighting/pull/877
- https://github.com/zsh-users/zsh-autosuggestions/pull/692

**Comment by ibayramli2001** [comment]
Thanks for raising these points @z0rc @syohex. 

> This text is pure advertisement with zero value

Fair point @z0rc, I totally see how this could've come across as too salesy. Yet, this is just the PR descriptionw which noone will see once it is closed. In fact, if it bothers the community so much, I am happy to edit the PR. My goal with putting 100k users was to show that Fig itself has its own large community, so a big number of people are likely to benefit from this change. 

> Link is just landing page and external image can be used for tracking. 

Re landing page - totally fair, but we're right now developing a deep link to the Fig application, so when Fig users click on that button, it will open the zsh-completions in Plugin Store on user's desktop. Therefore, we thought providing a button would express the destination of the button better than a hyperlink. We could have left it as a hyperlink and then made another PR when the deep link redirection is established, but we wanted to respect the maintainers' time and not make two PRs for one feature.  But I understand @z0rc how without providing this context the button could have seemed redundant. 

Re external image - excellent point @z0rc, thanks for raising it. Since tracking seems to be a concern for the community, we will host the image on github CDN so tracking is impossible and edit the PR to reflect that. @syohex does that sound good?

**Pull request merged**
