### PR TITLE
WIP: Improved Django completion

### PR DESCRIPTION
**Pull request by blueyed**
This has been in the works since a while locally.

The plan is to get this upstream into Zsh itself, but when using older versions of Zsh etc it might be useful to get into zsh-completions first.

There are some TODOs left, but in general it's good for feedback/testing.

I've merged changes from oh-my-zsh's plugin a while ago (have not checked it now again).

TODO
 - [ ] source attribution(s)

### CODE REVIEW

**Comment by nicoulaj** [comment]
You removed the header, can you put it back please ?

**Comment by blueyed** [comment]
Added a TODO.

**Comment by syohex** [comment]
Original file was removed at https://github.com/zsh-users/zsh-completions/commit/0713143ec8ffc55da4c9f81e475cd5e21f2771f4.

https://github.com/zsh-users/zsh-completions/issues/207

**Comment by blueyed** [comment]
Yeah, I've seen it yesterday.
I was not aware of #207, and need to come back to this PR.

**Comment by nicoulaj** [comment]
This is an old PR, I'm closing, please resubmit it if you feel it is ready for merge.

**Comment by blueyed** [comment]
Yeah, will reopen then.

For people finding this: I am using this myself, it works good, but needs to get cleaned up for submission here.

**Pull request closed without merging**
