### PR TITLE
add 'shellcheck' completion

### PR DESCRIPTION
**Pull request by Z5483**
- [x] This compdef is not already available in zsh.
- [x] This compdef is not already available in their original project.
- [x] I am the original author, or I have authorization to submit this work.
- [x] This is a finished work.
- [x] It has a header containing authors, status and origin of the script.
- [x] It has a license header or I accept that it will be licensed under the terms of the Zsh license.

### CODE REVIEW

**Comment by syohex** [comment]
How about like this without variable and state ? Global variable definitions affects globally and it is not preferable.

```zsh
_arguments -C \
  {-a,--check-sourced}'[Include warnings from sourced file]' \
  {-C,--color=}'[Use color]: :(auto always never)' \
  {-i,--include=}'[Consider only given types of warnings]:specify code' \
  {-e,--exclude=}'[Exclude types of warnings]:specify code' \
  {-f,--format}'[Output format]: :(checkstyle diff gcc json json1 quiet tty)' \
  '--list-optional[List checks disabled by default]' \
  '--norc[Do not look for .shellcheckrc files]' \
  {-o,--enable}'[List of optional checks to enable (or '\''all'\'')]' \
  {-P,--source-path=}'[Specify path when looking for sourced files]:_files -/' \
  {-s,--shell=}'[Specify dialect]: :(sh bash dash ksh)' \
  {-S,--severity=}'[Minimum severity of errors to consider]: :(error warning info style)' \
  {-V,--version}'[Print version information]' \
  {-W,--wiki-link-count=}'[The number of wiki links to show, when applicable]:specify number' \
  {-x,--external-sources}'[Allow outside sources]' \
  '--help[Show this usage summary and exit]' \
  '*: :_files'
```

And please put a license header.

**Comment by okapia** [comment]
> And please put a license header.

Given that "It has a license header or I accept that it will be licensed under the terms of the Zsh license." has been ticked, isn't that confirmation that Z5483 is happy for it to be distributed under the terms of the Zsh licence. Maybe the contribution header needs to force that to be more explicit.

The Zsh license should really always be the preferred choice because it is the only choice that makes it possible for zsh itself to include the completion function. There are fewer of them here precisely because they then often did then move to zsh itself. No header means the default choice - the Zsh licence.

**Comment by okapia** [comment]
> `_arguments -C \`

Without the states, `-C` won't be needed any more.
Also, check whether `-s` or `-S` or `-A` options are applicable. `-s` indicates that short options can be combined in a single word (e.g `-aWx`), `-S` indicates that `--` ends options to allow a file with a name starting with `-` and `-A` is used with a pattern to indicate that the first matching argument ends options (BSD rather than GNU style option parsers).

>`   {-a,--check-sourced}'[Include warnings from sourced file]' \`

Zsh convention is for lowercase in descriptions: "include…"
That applies throughout.

>   `{-C,--color=}'[Use color]: :(auto always never)' \`

This has lost the description from the original patch: the word color should appear in the blank between the colons. Eliding that description may be common where we call a function or state that adds one but when listing matches, as here, it is best included.

>`   '--norc[Do not look for .shellcheckrc files]' \`
>`   {-o,--enable}'[List of optional checks to enable (or '\''all'\'')]' \`

I find the quoting rather less messy by using double quotes when I want single quotes in a description. Single quotes inside of double quotes need no extra quoting. On the first of those lines, I'd even use the shorter "don't" for the wording. I find it less ugly this way:

```
   "--norc[don't look for .shellcheckrc files]" \
   {-o,--enable}"[list of optional checks to enable (or 'all')]" \
```

>`   {-S,--severity=}'[Minimum severity of errors to consider]: :(error warning info style)' \`
>`   {-W,--wiki-link-count=}'[The number of wiki links to show, when applicable]:specify number' \`

Use the imperitive mood form for per-match descriptions, i.e. add "specify" or "give" to the beginning of these descriptions. The existing "specify number" description should just be "number". That's used as a heading.

Aside from that, the function lacks exclusion lists on the options. These mark the options that are mutually exclusive. That isn't necessary as such but presenting fewer matches makes completion more useful.

**Comment by Z5483** [comment]
thank you for all the feedback!
I will fix the errors when I have time. Sorry for my sloppy PR!

**Review by syohex — APPROVED** [review]
Looks good

**Pull request merged**
