### PR TITLE
add terraform completion

### PR DESCRIPTION
**Pull request by knakayama**

### CODE REVIEW

**Comment by bosr** [comment]
+1, should be very useful, thanks!

**Comment by hhatto** [comment]
@knakayama 
Thank you for contribution.

code is looks good for me.
Could you please add a header?
see [here](https://github.com/zsh-users/zsh-completions/blob/master/src/_ack#L1-L40)

**Comment by hhatto** [comment]
Is looks good better to use it
https://github.com/hashicorp/terraform/blob/master/contrib/zsh-completion/_terraform

**Comment by knakayama** [comment]
@hhatto 
Sorry for this PR. I just wanted to add [the terraform completion](https://github.com/hashicorp/terraform/blob/master/contrib/zsh-completion/_terraform) to zsh-completions repository.
I agree with your judgment.

**Pull request closed without merging**
