### PR TITLE
Update _ag completion

### PR DESCRIPTION
**Pull request by starcraftman**
* Simplified parsing of filetypes, no more awk-fu!
* Added version based checks to complete only existing features
*   Due to ag's unstable nature, this will help completing right things based on version.
* Added missing opt --passthrough
* Lowercased all strings not 2 sentences
* Instead of just caching types, I'm caching the whole opts since the work for init setup increased.

Still outstanding question:
Not sure what to do with uppercased lines with multiple sentences.

### CODE REVIEW

**Comment by starcraftman** [comment]
@hhatto Seems like you gotten a bit busy, are there any other collaborators that could start looking over PRs here from zsh-usrs org? Seems a shame to let the completions project stagnate.

**Comment by hhatto** [comment]
@starcraftman 
Sorry for late reply.
merge this PR.

@nicoulaj @sorin-ionescu 
Could you ownership of this repository?

**Comment by sorin-ionescu** [comment]
@hhatto, as far as I recall, @nicoulaj started this project. I suppose I could pay attention to more Zsh projects than Prezto.

**Comment by hhatto** [comment]
> @hhatto, as far as I recall, @nicoulaj started this project. I suppose I could pay attention to more Zsh projects than Prezto.
Thank you.

> Could you ownership of this repository?
The reason, it is because I want to add it recruited collaborator.
It is not a silver bullet, but it might be able to some extent facilitate the project management I believe.

**Comment by starcraftman** [comment]
@hhatto Thanks for merging.

> The reason, it is because I want to add it recruited collaborator.
I think what you meant is you want @sorin-ionescu to give you ownership so you can add collaborators, right? Sounds good, would be nice to see some more activity. I'll probably look at updating ack next, already fixing up their bash completion.

**Comment by sorin-ionescu** [comment]
I understood that @hhatto wants me to take over the project from @nicoulaj to process the issues and pull requests.

**Comment by starcraftman** [comment]
@sorin-ionescu Perhaps @hhatto could clarify what he meant. Either way, thanks to both of you for your work :). I'll try to pitch in where I can, I'm still learning things about zsh.

**Comment by sorin-ionescu** [comment]
I'm not sure due to broken English.

**Pull request merged**
