### PR TITLE
Remove _trash* because trashcli support completion

### PR DESCRIPTION
**Pull request by Freed-Wu**
Trashcli has its own shell completion which support bash/zsh/tcsh.

https://github.com/andreafrancia/trash-cli/blob/master/trashcli/shell_completion.py

- [x] This compdef is not already available in zsh.
- [ ] This compdef is not already available in their original project.
- [ ] I am the original author, or I have authorization to submit this work.
- [x] This is a finished work.
- [ ] It has a header containing authors, status and origin of the script.
- [x] It has a license header or I accept that it will be licensed under the terms of the Zsh license.

### CODE REVIEW

**Comment by syohex** [comment]
BTW how do we use trash own shell completion ? It looks that there is no documentation about it. Is it easy to migrate from zsh-completions to its own completion ?

**Comment by Freed-Wu** [comment]
> there is no documentation about it

I notice it. It should be a forgiveness of the maintainer.

```sh
cmds=(trash-empty trash-list trash-restore trash-put trash)
for cmd in $cmds; do
  $cmd --print-completion bash | sudo tee /usr/share/bash-completion/completions/$cmd
  $cmd --print-completion zsh | sudo tee /usr/share/zsh/site-functions/_$cmd
  $cmd --print-completion tcsh | sudo tee /etc/profile.d/$cmd.completion.csh
done
```

So, `/usr/share/zsh/site-functions/trash*` must be removed to avoid conflicts.

**Comment by Freed-Wu** [comment]
Can we add one section to `README.md` about how to use shell completion? @andreafrancia

**Comment by andreafrancia** [comment]
Yes, sure just send me a pull request with the needed modifications for the README.

**Comment by andreafrancia** [comment]
@Freed-Wu, I've merged your pull request.

**Comment by syohex** [comment]
Thanks

**Pull request merged**
