### PR TITLE
Completion for 'udisksctl'

### PR DESCRIPTION
**Pull request by olejorgenb**
**NB:** Salvaged from rejected/ignored patch to upstream by Damir Jelić (poljar) [1]. (@poljar ?)

License is assumed to be gpl2 since it was submitted as a patch to udisks [2].

I tried contacting poljar, but the email address is no longer active.

[1] https://lists.freedesktop.org/archives/devkit-devel/2014-February/001554.html
[2] https://cgit.freedesktop.org/udisks/tree/tools

Hopefully the license inference is acceptable.

### CODE REVIEW

**Comment by poljar** [comment]
GPL2 is fine or ISC/MIT whichever one is preferred here.

Thanks for resurrecting this.

**Comment by syohex** [comment]
It looks new sub-command, `power-off`,  was added. Could you update completion file ?

**Comment by olejorgenb** [comment]
Done (also changed license to MIT per poljar's comment)

**Comment by syohex** [comment]
Merged

**Pull request merged**
