### PR TITLE
WIP: completion for pytest

### PR DESCRIPTION
**Pull request by blueyed**
This is WIP that needs to be cleaned up.

Inspired/based on https://github.com/alfredodeza/zsh-plugins/blob/master/pytest/pytest.plugin.zsh.

TODO:
 - [ ] caching based on Python sys.path and pytest location, see https://github.com/zsh-users/zsh-completions/pull/407/files#diff-0a6dd68ef4f6d05c6bbafad528caf849R381 and https://github.com/zsh-users/zsh-completions/pull/407/files#diff-0a6dd68ef4f6d05c6bbafad528caf849R453 (because you might have different plugins per venv etc)

### CODE REVIEW

**Comment by syohex** [comment]
Did you read https://github.com/zsh-users/zsh-completions#contributing ?

> Completions are not accepted when already available in their original project.

I suppose you should commit to original repository.

**Comment by blueyed** [comment]
There is no completion shipped with pytest already, but we might (https://github.com/pytest-dev/pytest/issues/1992).
In general I find it more convenient to have it automatically installed by using this repo.
I could also imagine adding it to Zsh itself, but that then needs time to trickle down to users not using the latest.

**Comment by nicoulaj** [comment]
I guess since they don't really have a zsh compdef in their project, we can have it here.

However we don't merge partial work, people tend to just forget about it after they add it here.

**Comment by blueyed** [comment]
Yeah, will reopen then (I've marked it as "WIP" to keep it on the radar, but can see that you rather have the PR queue empty).

For people finding this: I am using this myself, it works good, but needs to get cleaned up for submission here.

**Comment by blueyed** [comment]
@nicoulaj 
Sure, although that contradicts your previous comment.

But I think it is rather complete already in general, and TODOs can be addressed always later.

I've pushed a fixup with my current version (please squash-merge in case you want to take it already).

**Comment by blueyed** [comment]
Hmm, seems to not show up due to the PR being closed?!
The branch is here: https://github.com/blueyed/zsh-completions/tree/pytest

**Pull request closed without merging**
