### PR TITLE
add supervisorctl completion

### PR DESCRIPTION
**Pull request by mafrosis**
Completion for the `supervisorctl` command in supervisord.

### CODE REVIEW

**Comment by mafrosis** [comment]
I've completely rewritten what was supplied in the first P/R. Features:

a) understandable code, as completions go
b) smarter handling of completion for processes versus groups
c) start/stop/restart completions respect processes which are in the relevant state

**Comment by mafrosis** [comment]
Can anyone tell me what I need to do to get this merged? Thanks

**Comment by mafrosis** [comment]
Hello! This pull is now 365 days old. Can some one please advise on why it is not merged?

**Comment by msva** [comment]
Actually, because noone from contributors using supervisord to properly check completion and make sure that upstream really do not want to handle it. Anyway, I think, I can proxy-maintain it for you, if you would agree to track bugs about it and will @mention me on fix-PRs

**Comment by msva** [comment]
Although, I'm now in few-days-long trip on the train, and GH-for-android can't merge PRs anyway... :-/

**Pull request merged**
