### PR TITLE
Remove flameshot completion

### PR DESCRIPTION
**Pull request by syohex**
It is provided from original project now

- [x] This is a finished work.

See #762. flameshot provides its own completion file now.

### CODE REVIEW

**Comment by kapsh** [comment]
Sorry. It is me who added zsh support into flameshot's existing bash completion file because I never noticed that this project provides native one. If you think this one feels nicer to use, then it may be better to upstream it while removing here.

**Comment by syohex** [comment]
> If you think this one feels nicer to use, then it may be better to upstream it while removing here.

I suppose both provides same features. So we should remove our version by our policy.

**Comment by jetersen** [comment]
Could this be included in a new tag?

**Comment by syohex** [comment]
> Could this be included in a new tag?

No

**Comment by jetersen** [comment]
ah my issue was I had a leftover symlink inside my `~/.zinit/completions` 😅

**Pull request merged**
