### PR TITLE
ansible, ansible-playbook, ansible-galaxy completions

### PR DESCRIPTION
**Pull request by bosr**
I wrote three completion functions:
- `_ansible`
- `_ansible-playbook`
- `_ansible-galaxy`

for Ansible (an Automation Framework): http://ansible.org

I did not manage to get `_gnu_generic` function to work properly with the help option of ansible commands because of their formatting. Anyway the modules list and host file parsing --for patterns-- would not have been available. Hence these three functions.

As noted in the `_ansible*` files, the pattern completion works if `${ANSIBLE_HOSTS}` points to a hostfile or if `/etc/ansible/hosts` exists (or `/usr/local/etc/ansible/hosts` on OS X), according to the fallback mechanism expected by ansible.

Regards

### CODE REVIEW

**Comment by bosr** [comment]
rebased on master

**Comment by bosr** [comment]
Hi,

I'd like to know if you have comments/improvements for this PR? Any plans to merge it? Thanks!

Best regards

**Comment by hacfi** [comment]
Would be quite useful!

**Comment by rosstimson** [comment]
:+1:  Just what I've been looking for, hope this gets merged soon.

**Comment by bosr** [comment]
Me too ;) thanks for the support!

Romain

**Comment by bosr** [comment]
Hello @hhatto, do you have comments on this PR? Do you think it could be merged?
Thank for this excellent project.

**Comment by hhatto** [comment]
Sorry for the late reply.
merged.

ps.
Can you send a patch to follow the latest version if available? :-)

**Comment by bosr** [comment]
Hi Hideo,

No worries, thank you. 

I have no patch yet, but it's a good idea to check if it is needed. I will check. 

Romain

**Pull request merged**
