### PR TITLE
Add completion for fail2ban-client

### PR DESCRIPTION
**Pull request by xdch47**
- [x] This compdef is not already available in zsh.
- [x] This compdef is not already available in their original project.
- [x] I am the original author
- [x] This is a finished work.
- [x] It has a header containing authors, status and origin of the script.
- [x] I accept that it will be licensed under the terms of the Zsh license.

### CODE REVIEW

**Comment by xdch47** [comment]
cross-platform replacement pattern newline solution (likewise #666).

**Comment by syohex** [comment]
Sorry very late reply. macOS `sed` command does not support `-r` option.  Could you rewrite `sed` code without `-r` option ?

**Comment by xdch47** [comment]
okay - escaped `+` and `(` `)` in sed regex's

**Comment by syohex** [comment]
Thanks

**Pull request merged**
