### PR TITLE
Add complete go 1.5 completion

### PR DESCRIPTION
**Pull request by mikkeloscar**
This adds complete golang 1.5 completions. It is partly based on the completion from oh-my-zsh which should be reflected in the license header.

### CODE REVIEW

**Comment by martinp** [comment]
The one in oh-my-zsh was copied from the Go distribution, so there should probably be a "Go authors" copyright in there instead. See this commit for the last revision that existed in the Go repo: https://github.com/golang/go/blob/1ec56062ef6b256f8269e2ca8c5477e3a917331a/misc/zsh/go

It was deleted in https://github.com/golang/go/commit/ddbefae97ef0dd506da22eab811574d57a4f2a3b.

**Comment by mikkeloscar** [comment]
@martinp thanks for letting me know. I have updated authors and copyright year. Since I have based some of it on code made by oh-my-zsh I don't want to leave them out.

**Comment by martinp** [comment]
@mikkeloscar Great. Hoping this will be merged soon.

**Comment by nono** [comment]
Nice! Thanks for adding golang support

**Pull request merged**
