### PR TITLE
Add completion for git-revise

### PR DESCRIPTION
**Pull request by dancek**
- [x] This compdef is not already available in zsh.
- [x] This compdef is not already available in their original project.
- [x] I am the original author, or I have authorization to submit this work.
- [x] This is a finished work.
- [x] It has a header containing authors, status and origin of the script.
- [x] It has a license header or I accept that it will be licensed under the terms of the Zsh license.

### CODE REVIEW

**Comment by syohex** [comment]
Thanks for PR. However I suppose it is better to set exclude option as below. For example, `--autosquash` and `--no-autosquash`. If we specify `--autosquash` option, then we don't want to complete `--no-autosquash` option.

```diff
diff --git a/src/_git-revise b/src/_git-revise
index cc9f92c..850c1ca 100644
--- a/src/_git-revise
+++ b/src/_git-revise
@@ -31,18 +31,18 @@ _git-revise() {
   local curcontext="$curcontext" ret=1
 
   _arguments \
-    {-h,--help}'[show help message and exit]' \
+    '(- * 1)'{-h,--help}'[show help message and exit]' \
     '--ref[reference to update]: :__git-revise_branches' \
     '--reauthor[reset the author of the targeted commit]' \
-    '--version[show version number and exit]' \
-    {--edit,-e}'[edit commit message of targeted commit(s)]' \
-    '--autosquash[automatically apply fixup! and squash! commits to their targets]' \
-    '--no-autosquash[force disable revise.autoSquash behaviour]' \
+    '(- * 1)--version[show version number and exit]' \
+    '(--edit -e)'{--edit,-e}'[edit commit message of targeted commit(s)]' \
+    '(--no-autosquash)--autosquash[automatically apply fixup! and squash! commits to their targets]' \
+    '(--autosquash)--no-autosquash[force disable revise.autoSquash behaviour]' \
     '--no-index[ignore the index while rewriting history]' \
-    {--all,-a}'[stage all tracked files before running]' \
-    {--interactive,-i}'[interactively edit commit stack]' \
-    {--message,-m}'[specify commit message on command line]:MESSAGE:()' \
-    {--cut,-c}'[interactively cut a commit into two smaller commits]' \
+    '(--all -a)'{--all,-a}'[stage all tracked files before running]' \
+    '(--interactive -i)'{--interactive,-i}'[interactively edit commit stack]' \
+    '(--message -m)'{--message,-m}'[specify commit message on command line]:MESSAGE:()' \
+    '(--cut -c)'{--cut,-c}'[interactively cut a commit into two smaller commits]' \
     '1: :__git-revise_commits' && ret=0
```

**Comment by dancek** [comment]
Thanks for the help! This is a good idea, I just didn't know how to do it. I'll update the commit.

**Comment by dancek** [comment]
I re-read the relevant part of `zshcompsys` and wrote mutually exclusive groups as they're in the [git-revise source code](https://github.com/mystor/git-revise/blob/master/gitrevise/tui.py#L20-L85).

**Comment by syohex** [comment]
Thanks

**Pull request merged**
