### PR TITLE
Update collect workspaces command

### PR DESCRIPTION
**Pull request by syohex**
- [x] This compdef is not already available in zsh.
- [x] This compdef is not already available in their original project.
- [x] I am the original author, or I have authorization to submit this work.
- [x] This is a finished work.
- [x] It has a header containing authors, status and origin of the script.
- [x] It has a license header or I accept that it will be licensed under the terms of the Zsh license.

This is related to #802

### CODE REVIEW

**Comment by kachkaev** [comment]
Thanks for looking into this @syohex!

The change might be breaking of Yarn v1 users. We should probably use `yarn --version` in some kind of an `if` statement to avoid that. There are also calls to `yarn run --json`, which don’t work in Berry.

Broadly speaking, I wonder if the difference between Yarn Classic and Yarn berry is big enough to implement autocompletion in a separate file. So conceptually, there can be a single `if` statement triages between one mode or the other.

**Comment by syohex** [comment]
How about https://github.com/zsh-users/zsh-completions/pull/827/commits/2f54f2b21287a5753728feba1ae2abcbf9df2aab ?

**Comment by kachkaev** [comment]
I’m not an expert in shell scripts, but this looks like a step in the right direction 👍 Something similar should probably be done for calls to `yarn run --json` too. There may be more discrepancies, but `yarn workspaces info` & `yarn run --json` are only ones I’ve spotted so far.

**Comment by syohex** [comment]
I'm not familiar with yarn. Are there any alternative commands same as `yarn run --json` in yarn v2 or higher versions ? If there is not such command, it is necessary to parse package.json like `cat package.json | perl -0777 -MJSON::PP -n -E '$r = decode_json($_); say for keys %{$r->{scripts}}'`

**Comment by kachkaev** [comment]
I am still new to Yarn berry myself, so am not sure if my answer is 100% right. The `yarn run` command was added in https://github.com/yarnpkg/berry/pull/290 but I could not find `--json` there.

It might be possible to run `yarn run` and `run bin` and parse the output. It looks very similar for both commands.

**Comment by syohex** [comment]
I have updated without `yarn run --json` at https://github.com/zsh-users/zsh-completions/pull/827/commits/839df669222b7c25b8ffcacbcbd3f01c9154df24

**Comment by kachkaev** [comment]
Cool, thank you @syohex! I can try checking the new script over the weekend if time allows!

Looking into `node_modules/.bin` should work for most folks on both yarn versions. The only problem I can imagine is to do with the usage of [Yarn PnP](https://yarnpkg.com/features/pnp), which bypasses the creation of `node_modules` directory. It is enabled in Yarn v2 and v3 by default.

From my experience, Yarn PnP is still experimental and so has compatibility issues with some popular tools. Going forward, it’d be best to leverage `yarn run` and `yarn bin` because it’s the most robust source of truth possible, but I don’t see reasons why we can’t enable Yarn Berry + `node_modules` only as a mid step 🙂

**Comment by syohex** [comment]
I have update for no `node_modules` case https://github.com/zsh-users/zsh-completions/pull/827/commits/790890e25658f9b5c6ba68264d888a2b191b895e

**Pull request merged**
