### PR TITLE
Use OMZ completions-dir.txt to improve installation

### PR DESCRIPTION
**Pull request by felipecrs**
This implements https://github.com/ohmyzsh/ohmyzsh/pull/10565.

Fixes https://github.com/zsh-users/zsh-completions/issues/603.

### CODE REVIEW

**Comment by felipecrs** [comment]
Waiting for #603 before marking as ready to review.

**Comment by felipecrs** [comment]
My last commit addresses the concern raised in https://github.com/ohmyzsh/ohmyzsh/issues/10412#issuecomment-967214321, where multiple entries of `src` could end up being added to `fpath`.

The approach I used was taken from https://unix.stackexchange.com/a/62581/427940, and I would really like to know if there better or cleaner approaches out there for handling such a situation in ZSH.

**Comment by nicoulaj** [comment]
Hi, I understand this `completions-dir.txt` file is specific to OMZ ? I don't think this project should be polluted with this kind of plugin manager specific files, it just makes it harder for other packagers and users. Not a big deal, just my two cents.

**Comment by felipecrs** [comment]
Specific for now, this is a new feature that I'm introducing at https://github.com/ohmyzsh/ohmyzsh/pull/10565. Other package managers can also make use of it if they want.

Also, isn't https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions.plugin.zsh also specific to OMZ?

**Comment by nicoulaj** [comment]
The `<foo>.plugin.zsh` is the only convention that is widely adopted by "plugin managers".

Does anyone else have thoughts on this ?

**Comment by felipecrs** [comment]
@nicoulaj just to mention, I totally understand your reasonings.

I'm just trying to solve an outstanding incompatibility issue between this project and OMZ. But any better ideas are 100% welcome, of course.

**Comment by mcornella** [comment]
I agree, this solution is not elegant and any changes that we make need to be adopted by the majority of plugin managers. It seems that most PMs support changing `$fpath` in the `.plugin.zsh` file.

This is not taken into account in OMZ because the `compinit` call happens before the plugin.zsh file is read (this is to allow running `compdef` in the .plugin.zsh, most outstandingly used in the git plugin).

If there is a solution to allow support for completion changes in the .plugin.zsh file while running `compinit` later, this solution wouldn't even be needed. Other PMs seem to do this, so it looks to me like there's no need for this and we simply have to improve OMZ.

**Pull request closed without merging**
